-- Additive schema for application-managed authentication identities.
-- This migration intentionally creates no users and stores no plaintext secrets.
CREATE TABLE IF NOT EXISTS app_users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    role TEXT NOT NULL,
    school_id TEXT,
    municipality_id TEXT,
    school_ids TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    token_version BIGINT NOT NULL DEFAULT 1,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),

    CONSTRAINT app_users_username_format_check CHECK (
        username = BTRIM(username)
        AND CHAR_LENGTH(username) BETWEEN 1 AND 120
    ),
    CONSTRAINT app_users_password_hash_format_check CHECK (
        CHAR_LENGTH(password_hash) BETWEEN 20 AND 1024
    ),
    CONSTRAINT app_users_role_check CHECK (
        role IN ('teacher', 'municipality', 'system_admin')
    ),
    CONSTRAINT app_users_token_version_check CHECK (token_version >= 1),
    CONSTRAINT app_users_school_ids_format_check CHECK (
        ARRAY_POSITION(school_ids, '') IS NULL
    ),
    CONSTRAINT app_users_scope_check CHECK (
        (
            role = 'teacher'
            AND school_id IS NOT NULL
            AND municipality_id IS NULL
            AND school_ids = ARRAY[school_id]
        )
        OR
        (
            role = 'municipality'
            AND school_id IS NULL
            AND municipality_id IS NOT NULL
            AND CARDINALITY(school_ids) >= 1
        )
        OR
        (
            role = 'system_admin'
            AND school_id IS NULL
            AND municipality_id IS NULL
            AND CARDINALITY(school_ids) = 0
        )
    )
);

COMMENT ON TABLE app_users IS
    'Application authentication identities; password_hash must never be returned by the API.';
